# Collection of all ICG labels for standardization across repositories
- name: administrative
  color: 0052cc
  description: A backend/admin task that has no visible front-end impact

- name: blocked
  color: d93f0b
  description: Unable to progress due to something blocking

- name: breaking-change
  color: b60205
  description: Something that is critical to monitor

- name: bug
  color: d73a4a
  description: Something is not working

- name: ci
  color: b41ae6
  description: Changes for overall CI processes

- name: design
  color: d93f0b
  description: Requires design team integration

- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation

- name: duplicate
  color: cfd3d7
  description: This issue or pull request already exists

- name: feature
  color: a2eeef
  description: New feature or request

- name: github-actions
  color: 9531e4
  description: Things for actions

- name: good first issue
  color: 7057ff
  description: Good for newcomers

- name: help wanted
  color: 008672
  description: Extra attention is needed

- name: improvement
  color: 89419c
  description: An enhancement to existing functionality

- name: invalid
  color: e4e669
  description: This does not seem right

- name: maintenance
  color: 91417e
  description: Updates and other regular maintenance

- name: optimization
  color: fbca04
  description: Improvements to the system performance

- name: performance
  color: 9269df
  description: Changes for performance purposes

- name: question
  color: d876e3
  description: Further information is requested

- name: refactor
  color: 533052
  description: Refactoring for long-term maintenance

- name: security
  color: 995260
  description: A security-related change

- name: testing
  color: 48a4b6
  description: Testing and related changes

- name: wontfix
  color: ffffff
  description: This will not be worked on
