name: CI/CD

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    name: Build and Publish
    env:
      solution-path: './PATH_FROM_ROOT_TO.sln'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Install GitVersion
      run: dotnet tool install --global GitVersion.Tool

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true 

    # https://github.com/valadas/set-dnn-manifest-versions
    - name: Update Versions on DNN Modules
      uses: valadas/set-dnn-manifest-versions@v1
      with:
        version: ${{ steps.gitversion.outputs.majorMinorPatch }}
        includeSolutionInfo: true

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    
    - name: Restore NuGet Packages
      run: nuget restore "${{ env.solution-path }}"
    
    - name: Build the solution
      run: msbuild "${{ env.solution-path }}" /p:Configuration=Release;
      
    - name: Collect Installers
      if: github.event_name != 'pull_request'
      run: |
        md installers
        Get-ChildItem -Include *install.zip -Recurse | Copy-Item -Destination "installers\"
      shell: powershell
      working-directory: .\

    - name: Store Install Package
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v2
      with:
        name: installers
        path: './installers/**_install.zip'
        retention-days: 5 # only need long enough to test/validate
    
    
    
    
